---
- name: Join Kubernetes Master
  shell: "{{lookup('file', '/tmp/join.sh')}}"

- name: Mark workers prepared
  file:
    path: /opt/worker.txt
    state: touch
    mode: u+rw,g-wx,o-rwx
    modification_time: preserve
    access_time: preserve